version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/spidey-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/spidey-app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
