name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main
  pull_request:
    branches:
      - main  # Chạy cho pull request vào nhánh main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Chỉnh sửa nếu bạn cần phiên bản Node.js khác

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend  # Đảm bảo thư mục chính xác

    - name: Run backend tests
      run: npm test
      working-directory: ./backend  # Đảm bảo thư mục chính xác

    - name: Build backend
      run: npm run build  # Nếu bạn có lệnh build
      working-directory: ./backend

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend/spidey-app  # Đảm bảo thư mục chính xác

    - name: Run frontend tests
      run: npm test
      working-directory: ./frontend/spidey-app  # Đảm bảo thư mục chính xác

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend/spidey-app  # Đảm bảo thư mục chính xác
