name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend  # Thay đổi thư mục nếu cần

      - name: Run tests
        run: npm test
        working-directory: ./backend  # Thay đổi thư mục nếu cần

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/spidey-app  # Thay đổi thư mục nếu cần

      - name: Deploy
        run: echo "Deploy your application here"